//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nKnight.RBAC
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RBAC.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Administrator.
        /// </summary>
        internal static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Blue4 {
            get {
                object obj = ResourceManager.GetObject("Blue4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create an instance of this class. Please use the static members of the class..
        /// </summary>
        internal static string CanNotCreateClass {
            get {
                return ResourceManager.GetString("CanNotCreateClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current IPrincipal.IIdentiy object is of the type UserIdentity and contains the following properties:{0}.
        /// </summary>
        internal static string CustomUserInfo {
            get {
                return ResourceManager.GetString("CustomUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while checking username and  password. Please try again!.
        /// </summary>
        internal static string DataAccessException {
            get {
                return ResourceManager.GetString("DataAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not belong to the neccessary security role therefore you can not complete this operation..
        /// </summary>
        internal static string DoNotHaveRole {
            get {
                return ResourceManager.GetString("DoNotHaveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was not able to retrieve the list of security groups the user belongs to..
        /// </summary>
        internal static string ErrorReadingSecurityGroups {
            get {
                return ResourceManager.GetString("ErrorReadingSecurityGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was not able to retrieve the list of security rights the user has..
        /// </summary>
        internal static string ErrorReadingSecurityRights {
            get {
                return ResourceManager.GetString("ErrorReadingSecurityRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was not able to retrieve the user information for the user..
        /// </summary>
        internal static string ErrorReadingUserInfo {
            get {
                return ResourceManager.GetString("ErrorReadingUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current user does NOT have the permission to perform this operation..
        /// </summary>
        internal static string HasNotPermission {
            get {
                return ResourceManager.GetString("HasNotPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current user does have the permission to perform this operation..
        /// </summary>
        internal static string HasPermission {
            get {
                return ResourceManager.GetString("HasPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log &amp;Off.
        /// </summary>
        internal static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no connection string defined. Please check the .config file!.
        /// </summary>
        internal static string MissingConnectionString {
            get {
                return ResourceManager.GetString("MissingConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon manager.
        /// </summary>
        internal static string MissingInformation {
            get {
                return ResourceManager.GetString("MissingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no parameter name string defined. Please check the .config file!.
        /// </summary>
        internal static string MissingParamString {
            get {
                return ResourceManager.GetString("MissingParamString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no SQL command string defined. Please check the .config file!.
        /// </summary>
        internal static string MissingSqlString {
            get {
                return ResourceManager.GetString("MissingSqlString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify b&amp;udget.
        /// </summary>
        internal static string ModifyBudget {
            get {
                return ResourceManager.GetString("ModifyBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify i&amp;ventory.
        /// </summary>
        internal static string ModifyInventory {
            get {
                return ResourceManager.GetString("ModifyInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify pro&amp;fit.
        /// </summary>
        internal static string ModifyProfit {
            get {
                return ResourceManager.GetString("ModifyProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify reve&amp;nue.
        /// </summary>
        internal static string ModifyRevenue {
            get {
                return ResourceManager.GetString("ModifyRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a username and password!.
        /// </summary>
        internal static string NoValidUserNameOrPassword {
            get {
                return ResourceManager.GetString("NoValidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Power user.
        /// </summary>
        internal static string PowerUser {
            get {
                return ResourceManager.GetString("PowerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You passed the security role check and the operation has been completed..
        /// </summary>
        internal static string RoleOperationCompleted {
            get {
                return ResourceManager.GetString("RoleOperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string StandardPropertyName {
            get {
                return ResourceManager.GetString("StandardPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current IPrincipal.IIdentiy is of the standard IIdentity type contains the following properties:{0}.
        /// </summary>
        internal static string StandardUserInfo {
            get {
                return ResourceManager.GetString("StandardUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Super admin.
        /// </summary>
        internal static string SuperAdministrator {
            get {
                return ResourceManager.GetString("SuperAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;User info.
        /// </summary>
        internal static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View &amp;budget.
        /// </summary>
        internal static string ViewBudget {
            get {
                return ResourceManager.GetString("ViewBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View &amp;inventory.
        /// </summary>
        internal static string ViewInventory {
            get {
                return ResourceManager.GetString("ViewInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View &amp;profit.
        /// </summary>
        internal static string ViewProfit {
            get {
                return ResourceManager.GetString("ViewProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View &amp;revenue.
        /// </summary>
        internal static string ViewRevenue {
            get {
                return ResourceManager.GetString("ViewRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username and password you entered is not correct!.
        /// </summary>
        internal static string WrongUserNameAndPassword {
            get {
                return ResourceManager.GetString("WrongUserNameAndPassword", resourceCulture);
            }
        }
    }
}
